### ISSUE TITLE
Bundle exec vara build-pivotal . Errors out

### ISSUE THREAD

**Issue by rjain-pivotal** [pivotal-cf-experimental/example-kafka-on-demand-tile#1]
The command `bundle exec vara build-pivotal .` errors out with the error message

**RuntimeError: URL or AWS Config required to download!**

`ruby --version`
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]

` which vara`

/Users/rjain/.rvm/gems/ruby-2.3.0/bin/vara

```
Users/rjain/code/example-kafka-on-demand-tile/content_migrations/migrations.yml has been created
I, [2016-11-28T15:49:38.481219 #63947]  INFO -- Vara::Tarball: Beginning download of  to /Users/rjain/code/example-kafka-on-demand-tile/releases/on-demand-service-broker-0.9.0.tgz
bundler: failed to load command: vara (/Users/rjain/.rvm/gems/ruby-2.3.0/bin/vara)
**RuntimeError: URL or AWS Config required to download!**
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/downloader.rb:10:in `download'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/tarball.rb:40:in `download'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/tarball.rb:22:in `sync_local_copy'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/product_resource_downloader.rb:47:in `block in download_releases'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/product_resource_downloader.rb:44:in `each'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/product_resource_downloader.rb:44:in `download_releases'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/product_resource_downloader.rb:29:in `download'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/cli.rb:61:in `download_artifacts'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/lib/vara/cli.rb:84:in `build_pivotal'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/rjain/.rvm/gems/ruby-2.3.0/gems/vara-0.22.0/bin/vara:14:in `<top (required)>'
  /Users/rjain/.rvm/gems/ruby-2.3.0/bin/vara:23:in `load'
  /Users/rjain/.rvm/gems/ruby-2.3.0/bin/vara:23:in `<top (required)>'

```

**Comment by rjain-pivotal** [comment]
I think this is mismatch in the tar ball version

`ls -la releases/`
`.gitkeep                             on-demand-service-broker-0.12.0.tgz`

Whereas the script is expecting 
`/Users/rjain/code/example-kafka-on-demand-tile/content_migrations/migrations.yml has been created
I, [2016-11-28T15:54:59.151544 #63981]  INFO -- Vara::Tarball: Beginning download of  to /Users/rjain/code/example-kafka-on-demand-tile/releases/on-demand-service-broker-0.9.0.tgz`

**Comment by avade** [comment]
Yes, the current instructions state you need to download 0.9.0.

We are going to be bumping the version in the example this week.
